export const SITE_TITLE='skullwaves'
export const SITE_WEBNAME='skullwaves - homepage'
export const NAME='skullwaves'
export const SITE_DESCRIPTION='A crypto and tech junior life'
export const HOMEPAGE_URL='https://www.skullwaves.io/'
//social links
export const INSTAGRAM_URL='https://www.instagram.com/'
export const LINKEDIN_URL='https://www.linkedin.com/in/sixtus-nosike-3568a1211/'
export const GITHUB_URL='https://github.com/Sixtus32/skullwaves-homepage'
export const WHATSAPP_URL='https://api.whatsapp.com/send?phone=631929153&text=Hello, my is Sixtus Nosike'
export const DISCORD_URL='https://discord.com/'
